# This file may be used to create a conda environment using:
# $ conda create --name gprMax-Designer --file <this file>

name: gprMax-Designer
dependencies:
- python>=3.7
- h5py
- sortedcontainers
- pillow
- matplotlib
